### ISSUE TITLE
Segfault in libdricore

### ISSUE THREAD

**Issue by jaspervdj** [jaspervdj/JVGS#1]
It seems that jvgs can segfault libdricore, altough it is very hard to reproduce. Captured traceback:
#31754 0xb74ceaf8 in vbo_split_inplace () from /usr/lib/xorg/modules/dri/libdricore.so
#31755 0xb74cd911 in vbo_split_prims () from /usr/lib/xorg/modules/dri/libdricore.so
#31756 0xb74d5381 in _tnl_draw_prims () from /usr/lib/xorg/modules/dri/libdricore.so
#31757 0xb74d43fd in vbo_save_playback_vertex_list () from /usr/lib/xorg/modules/dri/libdricore.so
#31758 0xb743d06d in execute_list () from /usr/lib/xorg/modules/dri/libdricore.so
#31759 0xb74404c2 in _mesa_CallList () from /usr/lib/xorg/modules/dri/libdricore.so
#31760 0xb74bb790 in neutral_CallList () from /usr/lib/xorg/modules/dri/libdricore.so
#31761 0x080f2aaf in jvgs::video::ListManager::callList (this=0x8144660, list=@0xa0b7944) at /home/jaspe
#31762 0x080f7580 in jvgs::sketch::Sketch::render (this=0xa0b7930) at /home/jasper/Project/jvgs/src/sket
#31763 0x080e4216 in jvgs::game::Level::render (this=0xa084598) at /home/jasper/Project/jvgs/src/game/Le
#31764 0x080e796c in jvgs::game::LevelManager::run (this=0x81445f0) at /home/jasper/Project/jvgs/src/ga

I don't know whether this error is due to jvgs (unlikely?) or some other library.

**Comment by jaspervdj** [comment]
This is not caused by the JVGS code. I am closing this issue.
